baseURL = "https://example.com/"
languageCode = "en-us"
title = "Vultur Chile"
theme = "lekh"

[params]

Name = "Agent Smith"
About = "Hello"

<figure>
    <img src="/exampleSite/images/Imagotipo Extendido B.png"
    <figcaption>A single track trail outside of Albuquerque, New Mexico.</figcaption>
</figure>

Resume = "" # Add the filename with file extension.

