baseURL = "https://example.com/"
languageCode = "en-us"
title = "Vultur Chile"
theme = "lekh"

[params]

Name = "Agent Smith"
About = "Hello"

<img src="/exampleSite/images/Imagotipo Extendido B.png">


Resume = "" # Add the filename with file extension.

